subscription_id = "update your Subscription_id"
client_id = "update your client_id"
client_secret = "update your client_secret"
tenant_id = "update your tenant_id"
prefix = "give req prefix name"
noofvms = "give how many VM's are required"
deployregion = "select the region for deployment"